-   id: check-filename
    name: check filenaming in the repo
    description: Check for spaces in filename and check if it follows a naming convention.
    entry: filename.py
    language: python

-   id: check-version
    name: check language version in the commit
    description: Check if the language version follow a particular version
    entry: run_check_pytho_version.sh
    language: script
