apiVersion: v1
kind: Pod
metadata:
  name: my-linux-pod
spec:
  containers:
  - name: linux-container
    image: alpine:latest
    command: [ "/bin/sh", "-c", "while true; do echo 'Hello, Kubernetes!'; sleep 1; done" ]